#!/usr/bin/env bash

function state {
  STATE=$(bluetoothctl show | grep 'Powered' | awk '{print $2}')
  if [[ $STATE == 'yes' ]]; then echo 'on'
  else echo 'off'; fi
}

function toggle {
  if [[ $(state) = 'on' ]]; then bluetoothctl power off
  else bluetoothctl power on; fi
}

if [[ $1 == 'toggle' ]]; then toggle; fi