#!/usr/bin/env bash

function screen_icon {
    ARRAY=( '󰛩' '󱩎' '󱩏' '󱩐' '󱩑' '󱩒' '󱩓' '󱩔' '󱩕' '󱩖' '󰛨' )
    IND=$(( $(screen_level) / 10))
    echo ${ARRAY[$IND]}
}

function kbd_icon {
    ARRAY=( '󰛩' '󱩎' '󱩏' '󱩐' '󱩑' '󱩒' '󱩓' '󱩔' '󱩕' '󱩖' '󰛨' )
    IND=$(( $(kbd_level) / 10))
    echo ${ARRAY[$IND]}
}

function screen_level {
    echo $(brightnessctl info | grep Current | awk '{print $4}' | tr '%' ' ' | tr '(' ' ' | tr ')' ' ')
}

function kbd_level {
    echo $(brightnessctl -d asus::kbd_backlight info | grep Current | awk '{print $4}' | tr '%' ' ' | tr '(' ' ' | tr ')' ' ')
}

function raise_screen {
    brightnessctl set 5%+ -q
    update_screen
}

function lower_screen {
    brightnessctl set 5%- -q
    update_screen
}

function raise_kbd {
    brightnessctl -d asus::kbd_backlight set +1 -q
    update_kbd
}

function lower_kbd { 
    brightnessctl -d asus::kbd_backlight set 1- -q
    update_kbd
}

function update_kbd {
    eww update brightness="$(get)"
    ~/.config/eww/scripts/./osd $(kbd_icon) $(kbd_level)
}

function update_screen {
    eww update brightness="$(get)"
    ~/.config/eww/scripts/./osd $(screen_icon) $(screen_level)
}

function set_screen {
    brightnessctl set $1"%" -q
    eww update brightness="$(get)"
}

function get {
    echo "{
        \"kbd\": { \"level\": \"$(kbd_level)\", \"icon\": \"$(kbd_icon)\" },
        \"screen\": { \"level\": \"$(screen_level)\", \"icon\": \"$(screen_icon)\" }
    }"
}

if [[ $1 == 'get' ]]; then get; fi
if [[ $1 == 'kbd' ]] && [[ $2 == 'up'   ]]; then raise_kbd; fi
if [[ $1 == 'kbd' ]] && [[ $2 == 'down' ]]; then lower_kbd; fi
if [[ $1 == 'screen' ]] && [[ $2 == 'up'   ]]; then raise_screen; fi
if [[ $1 == 'screen' ]] && [[ $2 == 'down' ]]; then lower_screen; fi
if [[ $1 == 'set_screen' ]]; then set_screen $2; fi
