#!/usr/bin/env bash

if [ ! -f "$HOME/.local/bin/todo" ]; then
  exit 0
fi

if [[ $1 == 'get' ]]; then 
    $HOME/.local/bin/todo -j | jq -c

    while true; do
        inotifywait -q -e modify $HOME/Documents/todos.json
        $HOME/.local/bin/todo -j | jq -c
    done
fi
