#!/usr/bin/env bash

NUMBER_OF_WORKSPACES=6

window_class() {
    echo `hyprctl activewindow -j | jq --raw-output .class`
}

window_title() {
    echo `hyprctl activewindow -j | jq --raw-output .title`
}

workspaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 $NUMBER_OF_WORKSPACES | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

active() {
    echo `hyprctl activewindow | grep "workspace: " | cut -d' ' -f2`
}

active_empty() {
    WSPACES=$(workspaces)
    ACTIVE=$(active)
    let "i = $ACTIVE - 1"
    WINDOWS=$(echo $WSPACES | jq --raw-output .[$i].windows)
    if [[ $WINDOWS -gt 0 ]]; then
        echo 'false'
    else
        echo 'true'
    fi
}

function get {
    echo "{
        \"workspaces\": $(workspaces),
        \"active_empty\": $(active_empty),
        \"active\": $(active),
        \"window_class\": \"$(window_class)\",
        \"window_title\": \"$(window_title)\"
    }"
}

eww update window_manager="$(get)"
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    eww update window_manager="$(get)"
done