#!/usr/bin/env bash

function state {
    STATE=$(pgrep wlsunset)
    if [[ -z $STATE ]]; then echo 'off'
    else echo 'on'; fi
}

function icon {
    echo '󰖨'
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'on' ]]; then
        eww update night_light_state="{ \"state\": \"off\", \"icon\": \"$(icon)\"}"
        pkill wlsunset
    else 
        eww update night_light_state="{ \"state\": \"on\", \"icon\": \"$(icon)\"}"
        wlsunset -t 3400
    fi
}

function get {
    echo "{
        \"state\": \"$(state)\",
        \"icon\": \"$(icon)\"
    }"
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'get' ]]; then get; fi
