#!/usr/bin/env bash

function loop {
    LOOPSTATUS=$(playerctl -p $1 loop)
    if [[ $LOOPSTATUS == 'None'     ]]; then playerctl -p $1 loop Track; fi
    if [[ $LOOPSTATUS == 'Track'    ]]; then playerctl -p $1 loop Playlist; fi
    if [[ $LOOPSTATUS == 'Playlist' ]]; then playerctl -p $1 loop None; fi
}

if [[ $2 == 'up' ]];   then playerctl -p $1 next; fi
if [[ $2 == 'down' ]]; then playerctl -p $1 previous; fi
if [[ $2 == 'next' ]]; then playerctl -p $1 next; fi
if [[ $2 == 'prev' ]]; then playerctl -p $1 previous; fi
if [[ $2 == 'play-pause' ]]; then playerctl -p $1 play-pause; fi
if [[ $2 == 'loop' ]];     then loop $1; fi
if [[ $2 == 'shuffle' ]];  then playerctl -p $1 shuffle Toggle; fi
if [[ $2 == 'volume' ]];   then playerctl -p $1 volume "0.$3"; fi
if [[ $2 == 'position' && ! -z $3 ]]; then playerctl -p $1 position $3; fi