#!/usr/bin/env bash

function state {
    STATE=$(asusctl profile --profile-get | awk '{print $4}')
    if   [[ $STATE == 'Quiet' ]]; then echo 'off'
    elif [[ $STATE == 'Balanced' ]]; then echo 'off'
    else echo 'on'
    fi
}

function icon {
    STATE=$(asusctl profile --profile-get | awk '{print $4}')
    if [[ $STATE == 'Quiet' ]]; then echo '󰾆'; fi
    if [[ $STATE == 'Balanced' ]]; then echo '󰾅'; fi
    if [[ $STATE == 'Performance' ]]; then echo '󰓅'; fi
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'off' ]]; then
        asusctl profile --profile-set Performance
    else
        asusctl profile --profile-set Quiet
    fi

    eww update power="$(get)"
}

function get {
    echo "{
        \"state\": \"$(state)\",
        \"icon\": \"$(icon)\"
    }"
}

if [[ $1 == 'get' ]]; then get; fi
if [[ $1 == 'toggle' ]]; then toggle; fi