#!/usr/bin/env bash

function state {
    THEME=$(gsettings get org.gnome.desktop.interface color-scheme)
    if [[ $THEME == "'prefer-dark'" ]]; then echo 'on'
    else echo 'off'; fi
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'on' ]]; then
        gsettings set org.gnome.desktop.interface color-scheme "'default'"
        cp $HOME/.config/eww/scss/colors_light.scss $HOME/.config/eww/scss/colors.scss
        cp $HOME/.config/gtklock/style-light.css $HOME/.config/gtklock/style.css
        cp $HOME/.config/wezterm/charm-light.lua $HOME/.config/wezterm/theme.lua
    else
        gsettings set org.gnome.desktop.interface color-scheme "'prefer-dark'"
        cp $HOME/.config/eww/scss/colors_dark.scss $HOME/.config/eww/scss/colors.scss
        cp $HOME/.config/gtklock/style-dark.css $HOME/.config/gtklock/style.css
        cp $HOME/.config/wezterm/charm.lua $HOME/.config/wezterm/theme.lua
    fi

    eww update theme="$(get)"
    $HOME/.config/eww/scripts/./init
}

function get {
    icon='󱎖'
    if [[ $(state) == 'on' ]]; then icon='󰃛'; fi
    echo "{
        \"state\": \"$(state)\",
        \"icon\": \"$icon\" 
    }"
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'get' ]]; then get; fi
