#!/usr/bin/env bash

function state {
    THEME=$(gsettings get org.gnome.desktop.interface color-scheme)
    if [[ $THEME == "'prefer-dark'" ]]; then echo 'on'
    else echo 'off'; fi
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'on' ]]; then
        gsettings set org.gnome.desktop.interface color-scheme "'default'"
        cp $HOME/.config/kitty/gnome_light.conf $HOME/.config/kitty/gnome.conf
        cp $HOME/.config/eww/scss/colors_light.scss $HOME/.config/eww/scss/colors.scss
        cp $HOME/.config/rofi/config_light.rasi $HOME/.config/rofi/config.rasi
        cp $HOME/.config/gtklock/style-light.css $HOME/.config/gtklock/style.css
        cp $HOME/.config/swaync/style-light.css $HOME/.config/swaync/style.css
    else
        gsettings set org.gnome.desktop.interface color-scheme "'prefer-dark'"
        cp $HOME/.config/kitty/gnome_dark.conf $HOME/.config/kitty/gnome.conf
        cp $HOME/.config/eww/scss/colors_dark.scss $HOME/.config/eww/scss/colors.scss
        cp $HOME/.config/rofi/config_dark.rasi $HOME/.config/rofi/config.rasi
        cp $HOME/.config/gtklock/style-dark.css $HOME/.config/gtklock/style.css
        cp $HOME/.config/swaync/style-dark.css $HOME/.config/swaync/style.css
    fi

    swaync-client --reload-css
    eww update theme_state=$(state)
    eww update theme_icon=$(icon)
    bash $HOME/.config/eww/scripts/init
}

function icon {
    echo '󰃛'
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'state' ]]; then state; fi
if [[ $1 == 'icon' ]]; then icon; fi