#!/usr/bin/env bash

KEY=`cat $HOME/.config/eww/scripts/weather_key`
SZFVAR="3044774"
PEST="3054638"

## Get data
get_weather() {
    weather=`curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$KEY&id=$1&units=metric"`
    
    w_desc="Weather Unavailable"
    w_temp="-"
    w_feels="-"
    w_city="Nowhere"
    w_icon=""

    if [ ! -z "$weather" ]; then
        w_desc=`echo $weather | jq -r .weather[].description | head -1 | sed -e "s/\b\(.\)/\u\1/g"`
        w_temp=`echo $weather | jq -r .main.temp | cut -d "." -f 1`
        w_feels=`echo $weather | jq -r .main.feels_like`
        w_city=`echo $weather | jq -r .name`

        w_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
        if   [ "$w_icon_code" == "01d"  ]; then w_icon=" "; w_class="d clear"
        elif [ "$w_icon_code" == "01n"  ]; then w_icon=" "; w_class="n clear"
        elif [ "$w_icon_code" == "02d"  ]; then w_icon=" "; w_class="d clouds"
        elif [ "$w_icon_code" == "02n"  ]; then w_icon=" "; w_class="n clouds"
        elif [ "$w_icon_code" == "03d"  ]; then w_icon=" "; w_class="d clouds"
        elif [ "$w_icon_code" == "03n"  ]; then w_icon=" "; w_class="n clouds"
        elif [ "$w_icon_code" == "04d"  ]; then w_icon=" "; w_class="d clouds"
        elif [ "$w_icon_code" == "04n"  ]; then w_icon=" "; w_class="n clouds"
        elif [ "$w_icon_code" == "09d"  ]; then w_icon=" "; w_class="d rain"
        elif [ "$w_icon_code" == "09n"  ]; then w_icon=" "; w_class="n rain"
        elif [ "$w_icon_code" == "10d"  ]; then w_icon=" "; w_class="d rain"
        elif [ "$w_icon_code" == "10n"  ]; then w_icon=" "; w_class="n rain"
        elif [ "$w_icon_code" == "11d"  ]; then w_icon=" "; w_class="d thunderstorm"
        elif [ "$w_icon_code" == "11n"  ]; then w_icon=" "; w_class="n thunderstorm"
        elif [ "$w_icon_code" == "13d"  ]; then w_icon=" "; w_class="d snow"
        elif [ "$w_icon_code" == "13n"  ]; then w_icon=" "; w_class="n snow"
        elif [ "$w_icon_code" == "50d"  ]; then w_icon=" "; w_class="d mist"
        elif [ "$w_icon_code" == "50n"  ]; then w_icon=" "; w_class="n mist"
        fi
    fi

    echo "{
        \"desc\": \"$w_desc\",
        \"temp\": \"$w_temp\",
        \"icon\": \"$w_icon\",
        \"class\": \"$w_class\",
        \"feels\": \"$w_feels\",
        \"city\": \"$w_city\"
    }"
}

echo "[
    $(get_weather $PEST),
    $(get_weather $SZFVAR)
]"
