#!/usr/bin/env bash

function class {
    hyprctl activewindow -j | jq --raw-output .class
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $2}'
}

function title {
    hyprctl activewindow -j | jq --raw-output .title
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $3}'
}

if [[ $1 == 'title' ]]; then title; fi
if [[ $1 == 'class' ]]; then class; fi