env:
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: 'module'
rules:
  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  curly:
    - error
    - multi-or-nest
    - consistent
  dot-location:
    - error
    - property
  eol-last: error
  indent:
    - error
    - 4
    - SwitchCase: 1
  keyword-spacing:
    - error
    - before: true
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  padded-blocks:
    - error
    - never
    - allowSingleLineBlocks: false
  prefer-const: error
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  nonblock-statement-body-position:
    - error
    - below
  no-trailing-spaces:
    - error
  array-bracket-spacing:
    - error
    - never
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  object-curly-spacing: 
    - error
    - always
  no-useless-escape:
    - off
globals:
  pkg: readonly
  ags: readonly
  ARGV: readonly
  imports: readonly
  print: readonly
  console: readonly
  logError: readonly
