#!/usr/bin/env bash

function state {
    STATE=$(pgrep wlsunset)
    if [[ -z $STATE ]]; then echo 'off'
    else echo 'on'; fi
}

function icon {
    echo '󰖨'
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'on' ]]; then
        eww update night_light_icon=$(icon)
        eww update night_light_state=off
        pkill wlsunset
    else 
        eww update night_light_icon=$(icon)
        eww update night_light_state=on
        wlsunset -t 3400
    fi
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'state' ]]; then state; fi
if [[ $1 == 'icon' ]]; then icon; fi