#!/usr/bin/env bash

function state {
    STATE=$(asusctl profile --profile-get | awk '{print $4}')
    if   [[ $STATE == 'Quiet' ]]; then echo 'off'
    elif [[ $STATE == 'Balanced' ]]; then echo 'off'
    else echo 'on'
    fi
}

function icon {
    STATE=$(asusctl profile --profile-get | awk '{print $4}')
    if [[ $STATE == 'Quiet' ]]; then echo '󰾆'; fi
    if [[ $STATE == 'Balanced' ]]; then echo '󰾅'; fi
    if [[ $STATE == 'Performance' ]]; then echo '󰓅'; fi
}

function toggle {
    STATE=$(state)
    if [[ $STATE == 'off' ]]; then
        asusctl profile --profile-set Performance
    else
        asusctl profile --profile-set Quiet
    fi

    eww update power_icon=$(icon)
    eww update power_state=$(state)
}

if [[ $1 == 'icon' ]]; then icon; fi
if [[ $1 == 'state' ]]; then state; fi
if [[ $1 == 'toggle' ]]; then toggle; fi
