-- local null_ls = require("null-ls")
-- local eslint = require("eslint")

-- null_ls.setup({
--   sources = {
--     null_ls.builtins.diagnostics.eslint,
--     null_ls.builtins.code_actions.eslint,
--   },
-- })

-- eslint.setup({
--   bin = 'eslint', -- or `eslint_d`
--   code_actions = {
--     enable = true,
--     apply_on_save = {
--       enable = true,
--       types = { "directive", "problem", "suggestion", "layout" },
--     },
--     disable_rule_comment = {
--       enable = true,
--       location = "separate_line", -- or `same_line`
--     },
--   },
--   diagnostics = {
--     enable = true,
--     report_unused_disable_directives = false,
--     run_on = "save", -- or type
--   },
-- })
